customhost = "database-1.cqlgke9gy8b1.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tayyongsheng-employee"
customregion = "us-east-1"
